# Generated by Django 4.0.1 on 2023-02-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financial_fields',
            fields=[
                ('values', models.CharField(default='0', max_length=1000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
